# Generated by Django 5.1.2 on 2024-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='entrance_fee',
            new_name='entrance_fee_adult',
        ),
        migrations.AddField(
            model_name='resort',
            name='entrance_fee_discounted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
