# Generated by Django 5.1.2 on 2024-12-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_culturalattraction_falls_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalattraction',
            name='entrance_fee_adult',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='entrance_fee_discounted',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='location',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='culturalattraction',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='entrance_fee_adult',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='entrance_fee_discounted',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='falls',
            name='phone',
        ),
    ]
