# Generated by Django 5.1.2 on 2024-12-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_culturalattraction_entrance_fee_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalattraction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/'),
        ),
        migrations.AddField(
            model_name='falls',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/'),
        ),
    ]
