# Generated by Django 5.1.2 on 2024-10-23 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_resort_facebook_resort_gmail_resort_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/'),
        ),
        migrations.AddField(
            model_name='resort',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/'),
        ),
        migrations.AddField(
            model_name='resort',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/'),
        ),
        migrations.AddField(
            model_name='resort',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/'),
        ),
        migrations.AddField(
            model_name='resort',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='app/images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='finish',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
