# Generated by Django 5.1.2 on 2024-12-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_culturalattraction_image_falls_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('cultural_significance', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
