# Generated by Django 5.1.2 on 2024-10-23 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_resort_image_1_resort_image_2_resort_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
