# Generated by Django 5.1.2 on 2024-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_resort_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, upload_to='app/images/'),
        ),
    ]
