# Generated by Django 5.1.2 on 2024-12-17 01:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_activity_event_festival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('patron_saint', models.CharField(blank=True, max_length=255, null=True)),
                ('traditional_food', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='culturalattraction',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culturalattraction',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culturalattraction',
            name='cultural_practices',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culturalattraction',
            name='entrance_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='culturalattraction',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='culturalattraction',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='culturalattraction',
            name='visiting_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
