# Generated by Django 5.1.2 on 2024-12-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fiesta_culturalattraction_best_time_to_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
    ]
