# Generated by Django 5.1.2 on 2024-10-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_gmail_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pax',
            field=models.IntegerField(default=0),
        ),
    ]
