# Generated by Django 5.1.2 on 2024-10-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_room_pax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pax',
            new_name='entrance',
        ),
    ]
